debug: True
gpu_ids: "0"  # or [0] if expecting a list
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
downcast_bf16: no
machine_rank: 0
main_process_ip: null
main_process_port: 29502
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
use_cpu: false

deepspeed_config:
  train_batch_size: 8
  train_micro_batch_size_per_gpu: 2
  gradient_accumulation_steps: 4

  fp16:
    enabled: true
    loss_scale: 0
    loss_scale_window: 100
    hysteresis: 2
    min_loss_scale: 1

  zero_optimization:
    stage: 2
    offload_optimizer:
      device: cpu
      pin_memory: true
    allgather_partitions: true
    allgather_bucket_size: 200000000
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: 200000000
    contiguous_gradients: true

  gradient_clipping: 1.0
  steps_per_print: 100
  wall_clock_breakdown: false
